### ISSUE TITLE
Details on the inference process and reproducing the scores

### ISSUE THREAD

**Issue by hjoh01** [BianChang/pix2pix#3]
Hello,

Thank you for publishing your code online.
I have trained your model using the HEMIT dataset and attempted to reproduce the results presented in your paper. 
While I achieved similar R and PSNR metrics, the SSIM value decreased significantly.
I performed patch-wise inference (1024x1024) as per the post_process.py code.
Could you please share the details of the inference process for result reproduction? 
Additionally, if possible, would you be willing to release your checkpoint online?

**Comment by BianChang** [comment]
Hi,

Thank you for your interest in our work. We have uploaded the checkpoints to the main branch of our repository. You can find the download link and details in the README document.
